### ISSUE TITLE
dbref feature

### ISSUE THREAD

**Issue by ericxin1982** [v2kiran/PSLiteDB#21]
hi @v2kiran 

Just wondering whether there is dbref feature out of box I can use to include or link other collection?

Thanks
Eric Xin

**Comment by v2kiran** [comment]
Hi this feature is not implemented in Ps because I think it requires named classes(I could be wrong) ...anyway if someone has a way to implement it I am more than happy to receive a pull request.

**Comment by ericxin1982** [comment]
Thanks
