### ISSUE TITLE
Provide C# source for PSLiteDB.dll

### ISSUE THREAD

**Issue by mponton** [v2kiran/PSLiteDB#4]
Hi Kiran,

Any plan/interest in opening up your C# code for `PSLiteDB.dll` (i.e the whole solution's source code)?

I'm interested to use the module but I am concerned about the lack of sourc ode for the DLL.

I'd be happy to share any fixes/features in the future if any.

Thanks!

**Comment by v2kiran** [comment]
Hi Marco

the c# code is in the dev branch..I should probably move that to master but anyway the dev branch has the latest source code that was used to generate the module feel free to check that.

I would certainly welcome any contributions to this project.

**Comment by mponton** [comment]
My apologies Kiran! I completely missed that. 😞 

Thanks for sharing the project and the for quick reply to this ticket!
